# Config file for Air

# Root directory of your project
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  exclude = ["tmp/**","client/**","public/**"]
  include = ["**/*.go"]
  poll = false

[log]
  level = "debug"

[watcher]
  color = true
  debounce = 1000
  ignore = ["tmp/**","vendor/**","public/**"]

[misc]
clean_on_exit = true
